name: Build and Push Docker Image
on:
#  schedule:
    # Tự động chạy hàng ngày vào 0h theo múi giờ Việt Nam (UTC+7)
#    - cron: "0 17 * * *"
  workflow_dispatch: # Cho phép chạy thủ công nếu cần

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:  # ⭐ Thêm quyền ghi vào repo
      contents: write    
    steps:
      # Checkout code với đủ quyền
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Cần thiết để git push hoạt động
          
      # Cài đặt QEMU cho cross-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      # Cài đặt buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3        
        
      # Đăng nhập vào Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      # Build và push image đa nền tảng
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: bibica/fast-socks5-server-silent
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      # Tạo commit rỗng (để tránh tình huống "there hasn't been activity in this repository for at least 60 days")
      - name: Create empty commit to keep repo alive
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit --allow-empty -m "Keep repo active for scheduled workflows"
          git push
